sudo: required

language: node_js
node_js:
  - "8.4.0"

services:
  - docker

cache:
  directories:
    - docker
    - node_modules

script: npm run lint

before_deploy:
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  global:
    ENCRYPTION_LABEL: 1d97a522c7ba
    COMMIT_AUTHOR_NAME: Travis
    COMMIT_AUTHOR_EMAIL: bot@schoenwald.media
