sudo: required

language: node_js
node_js: 8.9.1

cache:
  directories:
    - docker

services:
  - docker

install:
  - echo "no install"

script: echo "nothing to see here"

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
  on:
    branch: master

branches:
  only:
    - master

env:
  global:
    ENCRYPTION_LABEL: 1d97a522c7ba
    COMMIT_AUTHOR_NAME: Travis
    COMMIT_AUTHOR_EMAIL: bot@schoenwald.media
