sudo: required

language: node_js
node_js:
  - "8.9.1"

services:
  - docker

before_install:
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

script: npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master

branches:
  only:
    - master

env:
  global:
    ENCRYPTION_LABEL: 1d97a522c7ba
    COMMIT_AUTHOR_NAME: Travis
    COMMIT_AUTHOR_EMAIL: bot@schoenwald.media
