language: ruby
node_js:
  - 2.3

before_install:
  - nvm install node
  - nvm use 6.1
  - npm install

before_script:
  - chmod +x ./deploy.sh
  - npm run lint

script: bash ./deploy.sh
branches:
  only:
    - master
env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    ENCRYPTION_LABEL: "1d97a522c7ba"
    COMMIT_AUTHOR_EMAIL: "bot@schoenwald.media"
