language: node_js
before_script:
  - bundle install --jobs=3 --retry=3 --deployment
  - chmod +x ./deploy.sh
script: bash ./deploy.sh
branches:
  only:
    - master
env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    ENCRYPTION_LABEL: "1d97a522c7ba"
    COMMIT_AUTHOR_EMAIL: "bot@schoenwald.media"
