language: node_js
before_script:
  - rvm install ruby-2.3.0
  - rvm use 2.3.0
  - bundle install --jobs=3 --retry=3 --deployment
  - chmod +x ./deploy.sh
script: bash ./deploy.sh
branches:
  only:
    - master
env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    ENCRYPTION_LABEL: "5e0dda776da3"
    COMMIT_AUTHOR_EMAIL: "bot@schoenwald.media"
