language: ruby
rvm:
  - 2.3.0

branches:
  only:
    - master

before_install:
  - bundle install
  - nvm install node
  - npm install

script: npm run lint

before_deploy:
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    ENCRYPTION_LABEL: "1d97a522c7ba"
    COMMIT_AUTHOR_EMAIL: "bot@schoenwald.media"
