
markdown: kramdown

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'Highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: [ 'csstargate.schoenwald.media' , 'www.rueckenwind-luebeck.de']

google_analytics: UA-33721620-2
google_site_verification: 3IKbfK2vAsnTUjCZC9pv2weEqymiNiNd7_pdhAHm1Z4


facebook:
  app_id: 481527111909443
  publisher: schoenwaldnils
  admins: schoenwaldnils

social:
  name: 'Nils Schönwald'
  links:
    - https://twitter.com/schoenwaldnils
    - https://github.com/schoenwaldnils
    - https://www.facebook.com/schoenwaldnils
    - https://www.linkedin.com/in/schoenwaldnils
    - https://plus.google.com/+NilsSch%C3%B6nwald

codepen:
  theme_id: 26304
  default_height: 300
  default_tabs: 'css,result'
  user:
    name: 'Nils Schönwald'
    slug: schoenwaldnils
