# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

general:
  branches:
    only:
     - master # list of branches to build
     - /feature/.*/ # or regexes

machine:
  services:
    - docker

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1


jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mkdir -p ~/repo
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test-css:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint CSS
          command: npm run stylelint

  test-js:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint JS
          command: npm run eslint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Export static files
          command: |
            set -x
            npm run export
            ls -a out

      - persist_to_workspace:
          root: ~/repo
          paths:
            - out

  test-html:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint HTML
          command: npm run htmlhint

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Server
          command: scp ./out/* deployer@5.35.245.22:/var/www/site/


workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout
      - test-css:
          requires:
            - checkout
      - test-js:
          requires:
            - checkout
      - build:
          requires:
            - test-css
      - test-html:
          requires:
            - build
      - deploy:
          requires:
            - test-html
          filters:
            branches:
              only: master
